export const LIST_MOVIESHOW_REQUEST = 'LIST_MOVIESHOW_REQUEST';
export const LIST_MOVIESHOW_SUCCESS = 'LIST_MOVIESHOW_SUCCESS';
export const LIST_MOVIESHOW_FAILURE = 'LIST_MOVIESHOW_FAILURE';
export const LIST_MOVIESHOW_IDLE = 'LIST_MOVIESHOW_IDLE';
